"""add phone number

Revision ID: 375c520f0ab0
Revises: 17eab2987aa9
Create Date: 2022-09-02 09:38:24.636854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375c520f0ab0'
down_revision = '17eab2987aa9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
